# Generated by Django 5.0.7 on 2024-07-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='', max_length=255)),
                ('Last_Name', models.CharField(default='', max_length=255)),
                ('Mobile_No', models.CharField(default='', max_length=255)),
                ('Email', models.EmailField(default='', max_length=255)),
                ('Password', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
