# Generated by Django 5.0.7 on 2024-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_re_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
